const packingData = {
    "date": "2024-08-07_11-08-27",
    "productTypes": [
        {
            "productTypeId": "productTypeId_1",
            "productType": "SCH 40 PVC NSF (Pools & Irrigation)",
            "skus": {
                "skuId_1": {
                    "skuId": "skuId_1",
                    "productTypeId": "productTypeId_1",
                    "displayOrder": 1,
                    "popularityScore": 5,
                    "productType": "SCH 40 PVC NSF (Pools & Irrigation)",
                    "SKU": "1/2\" PVC PIPE SCH 40 - BELL ENDED",
                    "eagleSticksPerBundle": "360",
                    "eagleBundlesPerTruckLoad": "36",
                    "eagleSticksPerTruckload": 12960,
                    "length": "20'",
                    "calculatedSticksPerBundle": 360,
                    "size": "1/2\""
                },
                "skuId_2": {
                    "skuId": "skuId_2",
                    "productTypeId": "productTypeId_1",
                    "displayOrder": 2,
                    "popularityScore": 5,
                    "productType": "SCH 40 PVC NSF (Pools & Irrigation)",
                    "SKU": "3/4\" PVC PIPE SCH 40 - BELL ENDED",
                    "eagleSticksPerBundle": "400",
                    "eagleBundlesPerTruckLoad": "24",
                    "eagleSticksPerTruckload": 9600,
                    "length": "20'",
                    "calculatedSticksPerBundle": 400,
                    "size": "3/4\""
                },
                "skuId_3": {
                    "skuId": "skuId_3",
                    "productTypeId": "productTypeId_1",
                    "displayOrder": 3,
                    "popularityScore": 5,
                    "productType": "SCH 40 PVC NSF (Pools & Irrigation)",
                    "SKU": "1\" PVC PIPE SCH 40 - BELL ENDED",
                    "eagleSticksPerBundle": "280",
                    "eagleBundlesPerTruckLoad": "20",
                    "eagleSticksPerTruckload": 5600,
                    "length": "20'",
                    "calculatedSticksPerBundle": 280,
                    "size": "1\""
                },
                "skuId_4": {
                    "skuId": "skuId_4",
                    "productTypeId": "productTypeId_1",
                    "displayOrder": 4,
                    "popularityScore": 8,
                    "productType": "SCH 40 PVC NSF (Pools & Irrigation)",
                    "SKU": "1 1/4\" PVC PIPE SCH 40 - BELL ENDED",
                    "eagleSticksPerBundle": "220",
                    "eagleBundlesPerTruckLoad": "24",
                    "eagleSticksPerTruckload": 5280,
                    "length": "20'",
                    "calculatedSticksPerBundle": 220,
                    "size": "1 1/4\""
                },
                "skuId_5": {
                    "skuId": "skuId_5",
                    "productTypeId": "productTypeId_1",
                    "displayOrder": 5,
                    "popularityScore": 2,
                    "productType": "SCH 40 PVC NSF (Pools & Irrigation)",
                    "SKU": "1 1/2\" PVC PIPE SCH 40 - BELL ENDED",
                    "eagleSticksPerBundle": "180",
                    "eagleBundlesPerTruckLoad": "24",
                    "eagleSticksPerTruckload": 4320,
                    "length": "20'",
                    "calculatedSticksPerBundle": 180,
                    "size": "1 1/2\""
                },
                "skuId_6": {
                    "skuId": "skuId_6",
                    "productTypeId": "productTypeId_1",
                    "displayOrder": 6,
                    "popularityScore": 1,
                    "productType": "SCH 40 PVC NSF (Pools & Irrigation)",
                    "SKU": "2\" PVC PIPE SCH 40 - BELL ENDED",
                    "eagleSticksPerBundle": "105",
                    "eagleBundlesPerTruckLoad": "24",
                    "eagleSticksPerTruckload": 2520,
                    "length": "20'",
                    "calculatedSticksPerBundle": 105,
                    "size": "2\""
                },
                "skuId_7": {
                    "skuId": "skuId_7",
                    "productTypeId": "productTypeId_1",
                    "displayOrder": 7,
                    "popularityScore": 2,
                    "productType": "SCH 40 PVC NSF (Pools & Irrigation)",
                    "SKU": "2 1/2\" PVC PIPE SCH 40 - BELL ENDED",
                    "eagleSticksPerBundle": "73",
                    "eagleBundlesPerTruckLoad": "24",
                    "eagleSticksPerTruckload": 1752,
                    "length": "20'",
                    "calculatedSticksPerBundle": 73,
                    "size": "2 1/2\""
                },
                "skuId_8": {
                    "skuId": "skuId_8",
                    "productTypeId": "productTypeId_1",
                    "displayOrder": 8,
                    "popularityScore": 3,
                    "productType": "SCH 40 PVC NSF (Pools & Irrigation)",
                    "SKU": "3\" PVC PIPE SCH 40 - BELL ENDED",
                    "eagleSticksPerBundle": "75",
                    "eagleBundlesPerTruckLoad": "16",
                    "eagleSticksPerTruckload": 1200,
                    "length": "20'",
                    "calculatedSticksPerBundle": 75,
                    "size": "3\""
                },
                "skuId_10": {
                    "skuId": "skuId_10",
                    "productTypeId": "productTypeId_1",
                    "displayOrder": 10,
                    "popularityScore": 6,
                    "productType": "SCH 40 PVC NSF (Pools & Irrigation)",
                    "SKU": "6\" PVC PIPE SCH 40 - BELL ENDED",
                    "eagleSticksPerBundle": "26",
                    "eagleBundlesPerTruckLoad": "12",
                    "eagleSticksPerTruckload": 312,
                    "length": "20'",
                    "calculatedSticksPerBundle": 26,
                    "size": "6\""
                },
                "skuId_11": {
                    "skuId": "skuId_11",
                    "productTypeId": "productTypeId_1",
                    "displayOrder": 11,
                    "popularityScore": 6,
                    "productType": "SCH 40 PVC NSF (Pools & Irrigation)",
                    "SKU": "8\" PVC PIPE SCH 40 - BELL ENDED",
                    "eagleSticksPerBundle": "15",
                    "eagleBundlesPerTruckLoad": "12",
                    "eagleSticksPerTruckload": 180,
                    "length": "20'",
                    "calculatedSticksPerBundle": 15,
                    "size": "8\""
                },
                "skuId_12": {
                    "skuId": "skuId_12",
                    "productTypeId": "productTypeId_1",
                    "displayOrder": 12,
                    "popularityScore": 6,
                    "productType": "SCH 40 PVC NSF (Pools & Irrigation)",
                    "SKU": "10\" PVC PIPE SCH 40 - BELL ENDED",
                    "eagleSticksPerBundle": "12",
                    "eagleBundlesPerTruckLoad": "12",
                    "eagleSticksPerTruckload": 144,
                    "length": "20'",
                    "calculatedSticksPerBundle": 12,
                    "size": "10\""
                },
                "skuId_13": {
                    "skuId": "skuId_13",
                    "productTypeId": "productTypeId_1",
                    "displayOrder": 13,
                    "popularityScore": 6,
                    "productType": "SCH 40 PVC NSF (Pools & Irrigation)",
                    "SKU": "12\" PVC PIPE SCH 40 - BELL ENDED",
                    "eagleSticksPerBundle": "6 / 8",
                    "eagleBundlesPerTruckLoad": "6 / 6",
                    "eagleSticksPerTruckload": 84,
                    "length": "20'",
                    "calculatedSticksPerBundle": 6,
                    "size": "12\""
                },
                "skuId_9": {
                    "skuId": "skuId_9",
                    "productTypeId": "productTypeId_1",
                    "displayOrder": 9,
                    "popularityScore": 4,
                    "productType": "SCH 40 PVC NSF (Pools & Irrigation)",
                    "SKU": "4\" PVC PIPE SCH 40 - BELL ENDED",
                    "eagleSticksPerBundle": "57",
                    "eagleBundlesPerTruckLoad": "12",
                    "eagleSticksPerTruckload": 684,
                    "length": "20'",
                    "calculatedSticksPerBundle": 57,
                    "size": "4\""
                }
            }
        },
        {
            "productTypeId": "productTypeId_2",
            "productType": "SCH 80 PVC (No NSF) Gray Pipe",
            "skus": {
                "skuId_14": {
                    "skuId": "skuId_14",
                    "productTypeId": "productTypeId_2",
                    "displayOrder": 14,
                    "popularityScore": 7,
                    "productType": "SCH 80 PVC (No NSF) Gray Pipe",
                    "SKU": "1/2\" PVC PIPE SCH 80 - PLAIN ENDED",
                    "eagleSticksPerBundle": "360",
                    "eagleBundlesPerTruckLoad": "36",
                    "eagleSticksPerTruckload": 12960,
                    "length": "20'",
                    "calculatedSticksPerBundle": 360,
                    "size": "1/2\""
                },
                "skuId_15": {
                    "skuId": "skuId_15",
                    "productTypeId": "productTypeId_2",
                    "displayOrder": 15,
                    "popularityScore": 7,
                    "productType": "SCH 80 PVC (No NSF) Gray Pipe",
                    "SKU": "3/4\" PVC PIPE SCH 80 - PLAIN ENDED",
                    "eagleSticksPerBundle": "400",
                    "eagleBundlesPerTruckLoad": "24",
                    "eagleSticksPerTruckload": 9600,
                    "length": "20'",
                    "calculatedSticksPerBundle": 400,
                    "size": "3/4\""
                },
                "skuId_16": {
                    "skuId": "skuId_16",
                    "productTypeId": "productTypeId_2",
                    "displayOrder": 16,
                    "popularityScore": 7,
                    "productType": "SCH 80 PVC (No NSF) Gray Pipe",
                    "SKU": "1\" PVC PIPE SCH 80 - PLAIN ENDED",
                    "eagleSticksPerBundle": "280",
                    "eagleBundlesPerTruckLoad": "20",
                    "eagleSticksPerTruckload": 5600,
                    "length": "20'",
                    "calculatedSticksPerBundle": 280,
                    "size": "1\""
                },
                "skuId_17": {
                    "skuId": "skuId_17",
                    "productTypeId": "productTypeId_2",
                    "displayOrder": 17,
                    "popularityScore": 7,
                    "productType": "SCH 80 PVC (No NSF) Gray Pipe",
                    "SKU": "1 1/4\" PVC PIPE SCH 80 - PLAIN ENDED",
                    "eagleSticksPerBundle": "220",
                    "eagleBundlesPerTruckLoad": "24",
                    "eagleSticksPerTruckload": 5280,
                    "length": "20'",
                    "calculatedSticksPerBundle": 220,
                    "size": "1 1/4\""
                },
                "skuId_18": {
                    "skuId": "skuId_18",
                    "productTypeId": "productTypeId_2",
                    "displayOrder": 18,
                    "popularityScore": 7,
                    "productType": "SCH 80 PVC (No NSF) Gray Pipe",
                    "SKU": "1 1/2\" PVC PIPE SCH 80 - PLAIN ENDED",
                    "eagleSticksPerBundle": "180",
                    "eagleBundlesPerTruckLoad": "24",
                    "eagleSticksPerTruckload": 4320,
                    "length": "20'",
                    "calculatedSticksPerBundle": 180,
                    "size": "1 1/2\""
                },
                "skuId_19": {
                    "skuId": "skuId_19",
                    "productTypeId": "productTypeId_2",
                    "displayOrder": 19,
                    "popularityScore": 7,
                    "productType": "SCH 80 PVC (No NSF) Gray Pipe",
                    "SKU": "2\" PVC PIPE SCH 80 - PLAIN ENDED",
                    "eagleSticksPerBundle": "105",
                    "eagleBundlesPerTruckLoad": "24",
                    "eagleSticksPerTruckload": 2520,
                    "length": "20'",
                    "calculatedSticksPerBundle": 105,
                    "size": "2\""
                },
                "skuId_20": {
                    "skuId": "skuId_20",
                    "productTypeId": "productTypeId_2",
                    "displayOrder": 20,
                    "popularityScore": 7,
                    "productType": "SCH 80 PVC (No NSF) Gray Pipe",
                    "SKU": "2 1/2\" PVC PIPE SCH 80 - PLAIN ENDED",
                    "eagleSticksPerBundle": "73",
                    "eagleBundlesPerTruckLoad": "24",
                    "eagleSticksPerTruckload": 1752,
                    "length": "20'",
                    "calculatedSticksPerBundle": 73,
                    "size": "2 1/2\""
                },
                "skuId_21": {
                    "skuId": "skuId_21",
                    "productTypeId": "productTypeId_2",
                    "displayOrder": 21,
                    "popularityScore": 7,
                    "productType": "SCH 80 PVC (No NSF) Gray Pipe",
                    "SKU": "3\" PVC PIPE SCH 80 - PLAIN ENDED",
                    "eagleSticksPerBundle": "75",
                    "eagleBundlesPerTruckLoad": "16",
                    "eagleSticksPerTruckload": 1200,
                    "length": "20'",
                    "calculatedSticksPerBundle": 75,
                    "size": "3\""
                },
                "skuId_22": {
                    "skuId": "skuId_22",
                    "productTypeId": "productTypeId_2",
                    "displayOrder": 22,
                    "popularityScore": 7,
                    "productType": "SCH 80 PVC (No NSF) Gray Pipe",
                    "SKU": "4\" PVC PIPE SCH 80 - PLAIN ENDED",
                    "eagleSticksPerBundle": "57",
                    "eagleBundlesPerTruckLoad": "12",
                    "eagleSticksPerTruckload": 684,
                    "length": "20'",
                    "calculatedSticksPerBundle": 57,
                    "size": "4\""
                },
                "skuId_23": {
                    "skuId": "skuId_23",
                    "productTypeId": "productTypeId_2",
                    "displayOrder": 23,
                    "popularityScore": 7,
                    "productType": "SCH 80 PVC (No NSF) Gray Pipe",
                    "SKU": "6\" PVC PIPE SCH 80 - PLAIN ENDED",
                    "eagleSticksPerBundle": "26",
                    "eagleBundlesPerTruckLoad": "12",
                    "eagleSticksPerTruckload": 312,
                    "length": "20'",
                    "calculatedSticksPerBundle": 26,
                    "size": "6\""
                },
                "skuId_24": {
                    "skuId": "skuId_24",
                    "productTypeId": "productTypeId_2",
                    "displayOrder": 24,
                    "popularityScore": 7,
                    "productType": "SCH 80 PVC (No NSF) Gray Pipe",
                    "SKU": "8\" PVC PIPE SCH 80 - PLAIN ENDED",
                    "eagleSticksPerBundle": "15",
                    "eagleBundlesPerTruckLoad": "12",
                    "eagleSticksPerTruckload": 180,
                    "length": "20'",
                    "calculatedSticksPerBundle": 15,
                    "size": "8\""
                }
            }
        },
        {
            "productTypeId": "productTypeId_3",
            "productType": "SDR 26 CL160 (Irrigation) Thin Wall (NSF)",
            "skus": {
                "skuId_25": {
                    "skuId": "skuId_25",
                    "productTypeId": "productTypeId_3",
                    "displayOrder": 25,
                    "popularityScore": 4,
                    "productType": "SDR 26 CL160 (Irrigation) Thin Wall (NSF)",
                    "SKU": "1/2\" SDR13.5 PVC PIPE IPS - BELL ENDED",
                    "eagleSticksPerBundle": "360",
                    "eagleBundlesPerTruckLoad": "36",
                    "eagleSticksPerTruckload": 12960,
                    "length": "20'",
                    "calculatedSticksPerBundle": 360,
                    "size": "1/2\""
                },
                "skuId_26": {
                    "skuId": "skuId_26",
                    "productTypeId": "productTypeId_3",
                    "displayOrder": 26,
                    "popularityScore": 4,
                    "productType": "SDR 26 CL160 (Irrigation) Thin Wall (NSF)",
                    "SKU": "3/4\" SDR26 PVC PIPE IPS - BELL ENDED",
                    "eagleSticksPerBundle": "400",
                    "eagleBundlesPerTruckLoad": "24",
                    "eagleSticksPerTruckload": 9600,
                    "length": "20'",
                    "calculatedSticksPerBundle": 400,
                    "size": "3/4\""
                },
                "skuId_27": {
                    "skuId": "skuId_27",
                    "productTypeId": "productTypeId_3",
                    "displayOrder": 27,
                    "popularityScore": 4,
                    "productType": "SDR 26 CL160 (Irrigation) Thin Wall (NSF)",
                    "SKU": "1\" SDR26 PVC PIPE IPS - BELL ENDED",
                    "eagleSticksPerBundle": "280",
                    "eagleBundlesPerTruckLoad": "20",
                    "eagleSticksPerTruckload": 5600,
                    "length": "20'",
                    "calculatedSticksPerBundle": 280,
                    "size": "1\""
                },
                "skuId_28": {
                    "skuId": "skuId_28",
                    "productTypeId": "productTypeId_3",
                    "displayOrder": 28,
                    "popularityScore": 4,
                    "productType": "SDR 26 CL160 (Irrigation) Thin Wall (NSF)",
                    "SKU": "1 1/4\" SDR26 PVC PIPE IPS - BELL ENDED",
                    "eagleSticksPerBundle": "220",
                    "eagleBundlesPerTruckLoad": "24",
                    "eagleSticksPerTruckload": 5280,
                    "length": "20'",
                    "calculatedSticksPerBundle": 220,
                    "size": "1 1/4\""
                },
                "skuId_29": {
                    "skuId": "skuId_29",
                    "productTypeId": "productTypeId_3",
                    "displayOrder": 29,
                    "popularityScore": 7,
                    "productType": "SDR 26 CL160 (Irrigation) Thin Wall (NSF)",
                    "SKU": "1 1/2\" SDR26 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "270",
                    "eagleBundlesPerTruckLoad": "16",
                    "eagleSticksPerTruckload": 4320,
                    "length": "20'",
                    "calculatedSticksPerBundle": 270,
                    "size": "1 1/2\""
                },
                "skuId_30": {
                    "skuId": "skuId_30",
                    "productTypeId": "productTypeId_3",
                    "displayOrder": 30,
                    "popularityScore": 7,
                    "productType": "SDR 26 CL160 (Irrigation) Thin Wall (NSF)",
                    "SKU": "2\" SDR26 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "185",
                    "eagleBundlesPerTruckLoad": "16",
                    "eagleSticksPerTruckload": 2960,
                    "length": "20'",
                    "calculatedSticksPerBundle": 185,
                    "size": "2\""
                },
                "skuId_31": {
                    "skuId": "skuId_31",
                    "productTypeId": "productTypeId_3",
                    "displayOrder": 31,
                    "popularityScore": 7,
                    "productType": "SDR 26 CL160 (Irrigation) Thin Wall (NSF)",
                    "SKU": "2 1/2\" SDR26 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "73",
                    "eagleBundlesPerTruckLoad": "28",
                    "eagleSticksPerTruckload": 2044,
                    "length": "20'",
                    "calculatedSticksPerBundle": 73,
                    "size": "2 1/2\""
                },
                "skuId_32": {
                    "skuId": "skuId_32",
                    "productTypeId": "productTypeId_3",
                    "displayOrder": 32,
                    "popularityScore": 7,
                    "productType": "SDR 26 CL160 (Irrigation) Thin Wall (NSF)",
                    "SKU": "3\" SDR26 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "75",
                    "eagleBundlesPerTruckLoad": "16",
                    "eagleSticksPerTruckload": 1200,
                    "length": "20'",
                    "calculatedSticksPerBundle": 75,
                    "size": "3\""
                },
                "skuId_33": {
                    "skuId": "skuId_33",
                    "productTypeId": "productTypeId_3",
                    "displayOrder": 33,
                    "popularityScore": 7,
                    "productType": "SDR 26 CL160 (Irrigation) Thin Wall (NSF)",
                    "SKU": "4\" SDR26 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "76",
                    "eagleBundlesPerTruckLoad": "12",
                    "eagleSticksPerTruckload": 912,
                    "length": "20'",
                    "calculatedSticksPerBundle": 76,
                    "size": "4\""
                },
                "skuId_34": {
                    "skuId": "skuId_34",
                    "productTypeId": "productTypeId_3",
                    "displayOrder": 34,
                    "popularityScore": 7,
                    "productType": "SDR 26 CL160 (Irrigation) Thin Wall (NSF)",
                    "SKU": "6\" SDR26 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "28 / 35",
                    "eagleBundlesPerTruckLoad": "4 / 8",
                    "eagleSticksPerTruckload": 392,
                    "length": "20'",
                    "calculatedSticksPerBundle": 28,
                    "size": "6\""
                },
                "skuId_35": {
                    "skuId": "skuId_35",
                    "productTypeId": "productTypeId_3",
                    "displayOrder": 35,
                    "popularityScore": 7,
                    "productType": "SDR 26 CL160 (Irrigation) Thin Wall (NSF)",
                    "SKU": "8\" SDR26 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "25 / 30",
                    "eagleBundlesPerTruckLoad": "4 / 4",
                    "eagleSticksPerTruckload": 220,
                    "length": "20'",
                    "calculatedSticksPerBundle": 25,
                    "size": "8\""
                },
                "skuId_36": {
                    "skuId": "skuId_36",
                    "productTypeId": "productTypeId_3",
                    "displayOrder": 36,
                    "popularityScore": 7,
                    "productType": "SDR 26 CL160 (Irrigation) Thin Wall (NSF)",
                    "SKU": "10\" SDR26 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "16 / 20",
                    "eagleBundlesPerTruckLoad": "4 / 4",
                    "eagleSticksPerTruckload": 144,
                    "length": "20'",
                    "calculatedSticksPerBundle": 16,
                    "size": "10\""
                },
                "skuId_37": {
                    "skuId": "skuId_37",
                    "productTypeId": "productTypeId_3",
                    "displayOrder": 37,
                    "popularityScore": 7,
                    "productType": "SDR 26 CL160 (Irrigation) Thin Wall (NSF)",
                    "SKU": "12\" SDR26 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "9 / 12 / 12 / 16",
                    "eagleBundlesPerTruckLoad": "2 / 2 / 2 / 2",
                    "eagleSticksPerTruckload": 98,
                    "length": "20'",
                    "calculatedSticksPerBundle": 12,
                    "size": "12\""
                }
            }
        },
        {
            "productTypeId": "productTypeId_4",
            "productType": "SDR 21 CL200 (Irrigation) Thin Wall (NSF)",
            "skus": {
                "skuId_38": {
                    "skuId": "skuId_38",
                    "productTypeId": "productTypeId_4",
                    "displayOrder": 38,
                    "popularityScore": 4,
                    "productType": "SDR 21 CL200 (Irrigation) Thin Wall (NSF)",
                    "SKU": "3/4\" SDR21 PVC PIPE IPS - BELL ENDED",
                    "eagleSticksPerBundle": "400",
                    "eagleBundlesPerTruckLoad": "24",
                    "eagleSticksPerTruckload": 9600,
                    "length": "20'",
                    "calculatedSticksPerBundle": 400,
                    "size": "3/4\""
                },
                "skuId_39": {
                    "skuId": "skuId_39",
                    "productTypeId": "productTypeId_4",
                    "displayOrder": 39,
                    "popularityScore": 4,
                    "productType": "SDR 21 CL200 (Irrigation) Thin Wall (NSF)",
                    "SKU": "1\" SDR21 PVC PIPE IPS - BELL ENDED",
                    "eagleSticksPerBundle": "280",
                    "eagleBundlesPerTruckLoad": "20",
                    "eagleSticksPerTruckload": 5600,
                    "length": "20'",
                    "calculatedSticksPerBundle": 280,
                    "size": "1\""
                },
                "skuId_40": {
                    "skuId": "skuId_40",
                    "productTypeId": "productTypeId_4",
                    "displayOrder": 40,
                    "popularityScore": 4,
                    "productType": "SDR 21 CL200 (Irrigation) Thin Wall (NSF)",
                    "SKU": "1 1/4\" SDR21 PVC PIPE IPS - BELL ENDED",
                    "eagleSticksPerBundle": "220",
                    "eagleBundlesPerTruckLoad": "24",
                    "eagleSticksPerTruckload": 5280,
                    "length": "20'",
                    "calculatedSticksPerBundle": 220,
                    "size": "1 1/4\""
                },
                "skuId_42": {
                    "skuId": "skuId_42",
                    "productTypeId": "productTypeId_4",
                    "displayOrder": 42,
                    "popularityScore": 7,
                    "productType": "SDR 21 CL200 (Irrigation) Thin Wall (NSF)",
                    "SKU": "2\" SDR21 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "185",
                    "eagleBundlesPerTruckLoad": "16",
                    "eagleSticksPerTruckload": 2960,
                    "length": "20'",
                    "calculatedSticksPerBundle": 185,
                    "size": "2\""
                },
                "skuId_43": {
                    "skuId": "skuId_43",
                    "productTypeId": "productTypeId_4",
                    "displayOrder": 43,
                    "popularityScore": 7,
                    "productType": "SDR 21 CL200 (Irrigation) Thin Wall (NSF)",
                    "SKU": "2 1/2\" SDR21 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "73",
                    "eagleBundlesPerTruckLoad": "28",
                    "eagleSticksPerTruckload": 2044,
                    "length": "20'",
                    "calculatedSticksPerBundle": 73,
                    "size": "2 1/2\""
                },
                "skuId_44": {
                    "skuId": "skuId_44",
                    "productTypeId": "productTypeId_4",
                    "displayOrder": 44,
                    "popularityScore": 7,
                    "productType": "SDR 21 CL200 (Irrigation) Thin Wall (NSF)",
                    "SKU": "3\" SDR21 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "75",
                    "eagleBundlesPerTruckLoad": "16",
                    "eagleSticksPerTruckload": 1200,
                    "length": "20'",
                    "calculatedSticksPerBundle": 75,
                    "size": "3\""
                },
                "skuId_45": {
                    "skuId": "skuId_45",
                    "productTypeId": "productTypeId_4",
                    "displayOrder": 45,
                    "popularityScore": 7,
                    "productType": "SDR 21 CL200 (Irrigation) Thin Wall (NSF)",
                    "SKU": "4\" SDR21 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "76",
                    "eagleBundlesPerTruckLoad": "12",
                    "eagleSticksPerTruckload": 912,
                    "length": "20'",
                    "calculatedSticksPerBundle": 76,
                    "size": "4\""
                },
                "skuId_46": {
                    "skuId": "skuId_46",
                    "productTypeId": "productTypeId_4",
                    "displayOrder": 46,
                    "popularityScore": 7,
                    "productType": "SDR 21 CL200 (Irrigation) Thin Wall (NSF)",
                    "SKU": "6\" SDR21 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "28 / 35",
                    "eagleBundlesPerTruckLoad": "4 / 8",
                    "eagleSticksPerTruckload": 392,
                    "length": "20'",
                    "calculatedSticksPerBundle": 28,
                    "size": "6\""
                },
                "skuId_47": {
                    "skuId": "skuId_47",
                    "productTypeId": "productTypeId_4",
                    "displayOrder": 47,
                    "popularityScore": 7,
                    "productType": "SDR 21 CL200 (Irrigation) Thin Wall (NSF)",
                    "SKU": "8\" SDR21 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "25 / 30",
                    "eagleBundlesPerTruckLoad": "4 / 4",
                    "eagleSticksPerTruckload": 220,
                    "length": "20'",
                    "calculatedSticksPerBundle": 25,
                    "size": "8\""
                },
                "skuId_48": {
                    "skuId": "skuId_48",
                    "productTypeId": "productTypeId_4",
                    "displayOrder": 48,
                    "popularityScore": 7,
                    "productType": "SDR 21 CL200 (Irrigation) Thin Wall (NSF)",
                    "SKU": "10\" SDR21 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "16 / 20",
                    "eagleBundlesPerTruckLoad": "4 / 4",
                    "eagleSticksPerTruckload": 144,
                    "length": "20'",
                    "calculatedSticksPerBundle": 16,
                    "size": "10\""
                },
                "skuId_49": {
                    "skuId": "skuId_49",
                    "productTypeId": "productTypeId_4",
                    "displayOrder": 49,
                    "popularityScore": 7,
                    "productType": "SDR 21 CL200 (Irrigation) Thin Wall (NSF)",
                    "SKU": "12\" SDR21 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "9 / 12 / 12 / 16",
                    "eagleBundlesPerTruckLoad": "2 / 2 / 2 / 2",
                    "eagleSticksPerTruckload": 98,
                    "length": "20'",
                    "calculatedSticksPerBundle": 12,
                    "size": "12\""
                },
                "skuId_41": {
                    "skuId": "skuId_41",
                    "productTypeId": "productTypeId_4",
                    "displayOrder": 41,
                    "popularityScore": 7,
                    "productType": "SDR 21 CL200 (Irrigation) Thin Wall (NSF)",
                    "SKU": "1 1/2\" SDR21 PVC PIPE IPS - GASKETED",
                    "eagleSticksPerBundle": "270",
                    "eagleBundlesPerTruckLoad": "16",
                    "eagleSticksPerTruckload": 4320,
                    "length": "20'",
                    "calculatedSticksPerBundle": 270,
                    "size": "1 1/2\""
                }
            }
        },
        {
            "productTypeId": "productTypeId_5",
            "productType": "C900 Blue Waterline Pipe (NSF)",
            "skus": {
                "skuId_50": {
                    "skuId": "skuId_50",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 50,
                    "popularityScore": 4,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "4\" DR14 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "60",
                    "eagleBundlesPerTruckLoad": "12",
                    "eagleSticksPerTruckload": 720,
                    "length": "20'",
                    "calculatedSticksPerBundle": 60,
                    "size": "4\""
                },
                "skuId_51": {
                    "skuId": "skuId_51",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 51,
                    "popularityScore": 4,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "6\" DR14 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "28",
                    "eagleBundlesPerTruckLoad": "12",
                    "eagleSticksPerTruckload": 336,
                    "length": "20'",
                    "calculatedSticksPerBundle": 28,
                    "size": "6\""
                },
                "skuId_52": {
                    "skuId": "skuId_52",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 52,
                    "popularityScore": 4,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "8\" DR14 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "15",
                    "eagleBundlesPerTruckLoad": "12",
                    "eagleSticksPerTruckload": 180,
                    "length": "20'",
                    "calculatedSticksPerBundle": 15,
                    "size": "8\""
                },
                "skuId_53": {
                    "skuId": "skuId_53",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 53,
                    "popularityScore": 8,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "10\" DR14 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "16",
                    "eagleBundlesPerTruckLoad": "8",
                    "eagleSticksPerTruckload": 128,
                    "length": "20'",
                    "calculatedSticksPerBundle": 16,
                    "size": "10\""
                },
                "skuId_54": {
                    "skuId": "skuId_54",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 54,
                    "popularityScore": 8,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "12\" DR14 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "4 / 6",
                    "eagleBundlesPerTruckLoad": "6 / 6",
                    "eagleSticksPerTruckload": 84,
                    "length": "20'",
                    "calculatedSticksPerBundle": 4,
                    "size": "12\""
                },
                "skuId_55": {
                    "skuId": "skuId_55",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 55,
                    "popularityScore": 4,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "4\" DR18 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "60",
                    "eagleBundlesPerTruckLoad": "12",
                    "eagleSticksPerTruckload": 720,
                    "length": "20'",
                    "calculatedSticksPerBundle": 60,
                    "size": "4\""
                },
                "skuId_56": {
                    "skuId": "skuId_56",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 56,
                    "popularityScore": 4,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "6\" DR18 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "28",
                    "eagleBundlesPerTruckLoad": "13",
                    "eagleSticksPerTruckload": 364,
                    "length": "20'",
                    "calculatedSticksPerBundle": 28,
                    "size": "6\""
                },
                "skuId_57": {
                    "skuId": "skuId_57",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 57,
                    "popularityScore": 4,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "8\" DR18 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "15 / 20",
                    "eagleBundlesPerTruckLoad": "8 / 4",
                    "eagleSticksPerTruckload": 200,
                    "length": "20'",
                    "calculatedSticksPerBundle": 15,
                    "size": "8\""
                },
                "skuId_58": {
                    "skuId": "skuId_58",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 58,
                    "popularityScore": 8,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "10\" DR18 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "16",
                    "eagleBundlesPerTruckLoad": "8",
                    "eagleSticksPerTruckload": 128,
                    "length": "20'",
                    "calculatedSticksPerBundle": 16,
                    "size": "10\""
                },
                "skuId_59": {
                    "skuId": "skuId_59",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 59,
                    "popularityScore": 8,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "12\" DR18 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "6 / 8 / 9 / 12",
                    "eagleBundlesPerTruckLoad": "4 / 4 / 2 / 2",
                    "eagleSticksPerTruckload": 98,
                    "length": "20'",
                    "calculatedSticksPerBundle": 8,
                    "size": "12\""
                },
                "skuId_60": {
                    "skuId": "skuId_60",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 60,
                    "popularityScore": 8,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "14\" DR18 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "9",
                    "eagleBundlesPerTruckLoad": "8",
                    "eagleSticksPerTruckload": 72,
                    "length": "20'",
                    "calculatedSticksPerBundle": 9,
                    "size": "14\""
                },
                "skuId_61": {
                    "skuId": "skuId_61",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 61,
                    "popularityScore": 9,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "16\" DR18 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "4 / 6 / 6 / 9",
                    "eagleBundlesPerTruckLoad": "2 / 2 / 2 / 2",
                    "eagleSticksPerTruckload": 50,
                    "length": "20'",
                    "calculatedSticksPerBundle": 6,
                    "size": "16\""
                },
                "skuId_62": {
                    "skuId": "skuId_62",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 62,
                    "popularityScore": 9,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "18\" DR18 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "4 / 6",
                    "eagleBundlesPerTruckLoad": "4 / 4",
                    "eagleSticksPerTruckload": 40,
                    "length": "20'",
                    "calculatedSticksPerBundle": 4,
                    "size": "18\""
                },
                "skuId_63": {
                    "skuId": "skuId_63",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 63,
                    "popularityScore": 9,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "20\" DR18 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "4",
                    "eagleBundlesPerTruckLoad": "8",
                    "eagleSticksPerTruckload": 32,
                    "length": "20'",
                    "calculatedSticksPerBundle": 4,
                    "size": "20\""
                },
                "skuId_64": {
                    "skuId": "skuId_64",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 64,
                    "popularityScore": 9,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "24\" DR18 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "3",
                    "eagleBundlesPerTruckLoad": "6",
                    "eagleSticksPerTruckload": 18,
                    "length": "20'",
                    "calculatedSticksPerBundle": 3,
                    "size": "24\""
                },
                "skuId_65": {
                    "skuId": "skuId_65",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 65,
                    "popularityScore": 5,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "4\" DR25 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "60",
                    "eagleBundlesPerTruckLoad": "12",
                    "eagleSticksPerTruckload": 720,
                    "length": "20'",
                    "calculatedSticksPerBundle": 60,
                    "size": "4\""
                },
                "skuId_66": {
                    "skuId": "skuId_66",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 66,
                    "popularityScore": 5,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "6\" DR25 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "28",
                    "eagleBundlesPerTruckLoad": "12",
                    "eagleSticksPerTruckload": 336,
                    "length": "20'",
                    "calculatedSticksPerBundle": 28,
                    "size": "6\""
                },
                "skuId_68": {
                    "skuId": "skuId_68",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 68,
                    "popularityScore": 9,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "10\" DR25 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "16",
                    "eagleBundlesPerTruckLoad": "8",
                    "eagleSticksPerTruckload": 128,
                    "length": "20'",
                    "calculatedSticksPerBundle": 16,
                    "size": "10\""
                },
                "skuId_69": {
                    "skuId": "skuId_69",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 69,
                    "popularityScore": 9,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "12\" DR25 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "6 / 8 / 9 / 12",
                    "eagleBundlesPerTruckLoad": "4 / 4 / 2 / 2",
                    "eagleSticksPerTruckload": 98,
                    "length": "20'",
                    "calculatedSticksPerBundle": 8,
                    "size": "12\""
                },
                "skuId_70": {
                    "skuId": "skuId_70",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 70,
                    "popularityScore": 9,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "14\" DR25 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "9",
                    "eagleBundlesPerTruckLoad": "8",
                    "eagleSticksPerTruckload": 72,
                    "length": "20'",
                    "calculatedSticksPerBundle": 9,
                    "size": "14\""
                },
                "skuId_71": {
                    "skuId": "skuId_71",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 71,
                    "popularityScore": 9,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "16\" DR25 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "4 / 6 / 6 / 9",
                    "eagleBundlesPerTruckLoad": "2 / 2 / 2 / 2",
                    "eagleSticksPerTruckload": 50,
                    "length": "20'",
                    "calculatedSticksPerBundle": 6,
                    "size": "16\""
                },
                "skuId_72": {
                    "skuId": "skuId_72",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 72,
                    "popularityScore": 9,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "18\" DR25 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "4 / 6",
                    "eagleBundlesPerTruckLoad": "4 / 4",
                    "eagleSticksPerTruckload": 40,
                    "length": "20'",
                    "calculatedSticksPerBundle": 4,
                    "size": "18\""
                },
                "skuId_73": {
                    "skuId": "skuId_73",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 73,
                    "popularityScore": 9,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "20\" DR25 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "4",
                    "eagleBundlesPerTruckLoad": "8",
                    "eagleSticksPerTruckload": 32,
                    "length": "20'",
                    "calculatedSticksPerBundle": 4,
                    "size": "20\""
                },
                "skuId_74": {
                    "skuId": "skuId_74",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 74,
                    "popularityScore": 9,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "24\" DR25 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "3",
                    "eagleBundlesPerTruckLoad": "9",
                    "eagleSticksPerTruckload": 18,
                    "length": "20'",
                    "calculatedSticksPerBundle": 3,
                    "size": "24\""
                },
                "skuId_67": {
                    "skuId": "skuId_67",
                    "productTypeId": "productTypeId_5",
                    "displayOrder": 67,
                    "popularityScore": 5,
                    "productType": "C900 Blue Waterline Pipe (NSF)",
                    "SKU": "8\" DR25 PVC PIPE C900 - GASKETED",
                    "eagleSticksPerBundle": "15 / 20",
                    "eagleBundlesPerTruckLoad": "8 / 4",
                    "eagleSticksPerTruckload": 200,
                    "length": "20'",
                    "calculatedSticksPerBundle": 15,
                    "size": "8\""
                }
            }
        },
        {
            "productTypeId": "productTypeId_6",
            "productType": "Green Sanitary Gravity Sewer Pipe (No NSF)",
            "skus": {
                "skuId_75": {
                    "skuId": "skuId_75",
                    "productTypeId": "productTypeId_6",
                    "displayOrder": 75,
                    "popularityScore": 4,
                    "productType": "Green Sanitary Gravity Sewer Pipe (No NSF)",
                    "SKU": "4\" SDR26 PVC PIPE GRAVITY SEWER - GASKETED",
                    "eagleSticksPerBundle": "84",
                    "eagleBundlesPerTruckLoad": "18",
                    "eagleSticksPerTruckload": 1512,
                    "length": "14'",
                    "calculatedSticksPerBundle": 84,
                    "size": "4\""
                },
                "skuId_76": {
                    "skuId": "skuId_76",
                    "productTypeId": "productTypeId_6",
                    "displayOrder": 76,
                    "popularityScore": 4,
                    "productType": "Green Sanitary Gravity Sewer Pipe (No NSF)",
                    "SKU": "6\" SDR26 PVC PIPE GRAVITY SEWER - GASKETED",
                    "eagleSticksPerBundle": "40",
                    "eagleBundlesPerTruckLoad": "18",
                    "eagleSticksPerTruckload": 720,
                    "length": "14'",
                    "calculatedSticksPerBundle": 40,
                    "size": "6\""
                },
                "skuId_77": {
                    "skuId": "skuId_77",
                    "productTypeId": "productTypeId_6",
                    "displayOrder": 77,
                    "popularityScore": 7,
                    "productType": "Green Sanitary Gravity Sewer Pipe (No NSF)",
                    "SKU": "8\" SDR26 PVC PIPE GRAVITY SEWER - GASKETED",
                    "eagleSticksPerBundle": "30 / 36",
                    "eagleBundlesPerTruckLoad": "6 / 6",
                    "eagleSticksPerTruckload": 396,
                    "length": "14'",
                    "calculatedSticksPerBundle": 30,
                    "size": "8\""
                },
                "skuId_78": {
                    "skuId": "skuId_78",
                    "productTypeId": "productTypeId_6",
                    "displayOrder": 78,
                    "popularityScore": 7,
                    "productType": "Green Sanitary Gravity Sewer Pipe (No NSF)",
                    "SKU": "10\" SDR26 PVC PIPE GRAVITY SEWER - GASKETED",
                    "eagleSticksPerBundle": "12 / 15",
                    "eagleBundlesPerTruckLoad": "9 / 9",
                    "eagleSticksPerTruckload": 243,
                    "length": "14'",
                    "calculatedSticksPerBundle": 12,
                    "size": "10\""
                },
                "skuId_79": {
                    "skuId": "skuId_79",
                    "productTypeId": "productTypeId_6",
                    "displayOrder": 79,
                    "popularityScore": 7,
                    "productType": "Green Sanitary Gravity Sewer Pipe (No NSF)",
                    "SKU": "12\" SDR26 PVC PIPE GRAVITY SEWER - GASKETED",
                    "eagleSticksPerBundle": "12 / 16",
                    "eagleBundlesPerTruckLoad": "6 / 6",
                    "eagleSticksPerTruckload": 168,
                    "length": "14'",
                    "calculatedSticksPerBundle": 12,
                    "size": "12\""
                },
                "skuId_80": {
                    "skuId": "skuId_80",
                    "productTypeId": "productTypeId_6",
                    "displayOrder": 80,
                    "popularityScore": 4,
                    "productType": "Green Sanitary Gravity Sewer Pipe (No NSF)",
                    "SKU": "4\" SDR35 PVC PIPE GRAVITY SEWER - GASKETED",
                    "eagleSticksPerBundle": "84",
                    "eagleBundlesPerTruckLoad": "18",
                    "eagleSticksPerTruckload": 1512,
                    "length": "14'",
                    "calculatedSticksPerBundle": 84,
                    "size": "4\""
                },
                "skuId_81": {
                    "skuId": "skuId_81",
                    "productTypeId": "productTypeId_6",
                    "displayOrder": 81,
                    "popularityScore": 4,
                    "productType": "Green Sanitary Gravity Sewer Pipe (No NSF)",
                    "SKU": "6\" SDR35 PVC PIPE GRAVITY SEWER - GASKETED",
                    "eagleSticksPerBundle": "40",
                    "eagleBundlesPerTruckLoad": "19",
                    "eagleSticksPerTruckload": 720,
                    "length": "14'",
                    "calculatedSticksPerBundle": 40,
                    "size": "6\""
                },
                "skuId_82": {
                    "skuId": "skuId_82",
                    "productTypeId": "productTypeId_6",
                    "displayOrder": 82,
                    "popularityScore": 6,
                    "productType": "Green Sanitary Gravity Sewer Pipe (No NSF)",
                    "SKU": "8\" SDR35 PVC PIPE GRAVITY SEWER - GASKETED",
                    "eagleSticksPerBundle": "30 / 36",
                    "eagleBundlesPerTruckLoad": "6 / 6",
                    "eagleSticksPerTruckload": 396,
                    "length": "14'",
                    "calculatedSticksPerBundle": 30,
                    "size": "8\""
                },
                "skuId_83": {
                    "skuId": "skuId_83",
                    "productTypeId": "productTypeId_6",
                    "displayOrder": 83,
                    "popularityScore": 9,
                    "productType": "Green Sanitary Gravity Sewer Pipe (No NSF)",
                    "SKU": "10\" SDR35 PVC PIPE GRAVITY SEWER - GASKETED",
                    "eagleSticksPerBundle": "12 / 15",
                    "eagleBundlesPerTruckLoad": "9 / 9",
                    "eagleSticksPerTruckload": 243,
                    "length": "14'",
                    "calculatedSticksPerBundle": 12,
                    "size": "10\""
                },
                "skuId_84": {
                    "skuId": "skuId_84",
                    "productTypeId": "productTypeId_6",
                    "displayOrder": 84,
                    "popularityScore": 9,
                    "productType": "Green Sanitary Gravity Sewer Pipe (No NSF)",
                    "SKU": "12\" SDR35 PVC PIPE GRAVITY SEWER - GASKETED",
                    "eagleSticksPerBundle": "12 / 16",
                    "eagleBundlesPerTruckLoad": "6 / 6",
                    "eagleSticksPerTruckload": 168,
                    "length": "14'",
                    "calculatedSticksPerBundle": 12,
                    "size": "12\""
                }
            }
        }
    ]
};